// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcEDKNefpDCUEA2alb260LbHJomwoQOus',
    appId: '1:119199614362:web:8f1e0d8a9f8d2cc95aa623',
    messagingSenderId: '119199614362',
    projectId: 'detection-pushnoti',
    authDomain: 'detection-pushnoti.firebaseapp.com',
    storageBucket: 'detection-pushnoti.firebasestorage.app',
    measurementId: 'G-8MKB0RKY57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb12gHo_3oEPLuD0K6LhE4NEPFcL5u4Us',
    appId: '1:119199614362:android:ce088cd48eed766e5aa623',
    messagingSenderId: '119199614362',
    projectId: 'detection-pushnoti',
    storageBucket: 'detection-pushnoti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2cuoNi-EtdJfnKORT4lFW9H8uafC07Vk',
    appId: '1:119199614362:ios:0da56369e062616a5aa623',
    messagingSenderId: '119199614362',
    projectId: 'detection-pushnoti',
    storageBucket: 'detection-pushnoti.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2cuoNi-EtdJfnKORT4lFW9H8uafC07Vk',
    appId: '1:119199614362:ios:0da56369e062616a5aa623',
    messagingSenderId: '119199614362',
    projectId: 'detection-pushnoti',
    storageBucket: 'detection-pushnoti.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcEDKNefpDCUEA2alb260LbHJomwoQOus',
    appId: '1:119199614362:web:7f655094f6bb8bdb5aa623',
    messagingSenderId: '119199614362',
    projectId: 'detection-pushnoti',
    authDomain: 'detection-pushnoti.firebaseapp.com',
    storageBucket: 'detection-pushnoti.firebasestorage.app',
    measurementId: 'G-4YQ7CHRWPP',
  );
}
